################
# Configuration
################
query FetchLoyaltyConfiguraion {
  fetchLoyaltyConfiguration {
    _id
    pointsPerDollar
  }
}

mutation SetLoyaltyConfiguration($input: LoyaltyConfigurationInput) {
  setLoyaltyConfiguration(input: $input) {
    _id
    pointsPerDollar
  }
}

############
# Level
############
query FetchLoyaltyLevelById($id: String!) {
  fetchLoyaltyLevelById(id: $id) {
    _id
    name
    amount
    points
  }
}

query FetchLoyaltyLevelsByUserType($userType: String!) {
  fetchLoyaltyLevelsByUserType(userType: $userType) {
    _id
    name
    amount
    points
  }
}

mutation CreateLoyaltyLevel($input: LoyaltyLevelInput!) {
  createLoyaltyLevel(input: $input) {
    _id
    name
    amount
    points
  }
}

mutation EditLoyaltyLevel($id: String!, $input: UpdateLoyaltyLevelInput!) {
  updateLoyaltyLevel(id: $id, input: $input) {
    _id
    name
    amount
    points
  }
}

mutation DeleteLoyaltyLevel($id: String!) {
  deleteLoyaltyLevel(id: $id) {
    _id
    name
    amount
    points
  }
}

############
# Tier
############
query FetchLoyaltyTierById($id: String!) {
  fetchLoyaltyTierById(id: $id) {
    _id
    name
    points
  }
}

query FetchLoyaltyTiers {
  fetchLoyaltyTiers {
    _id
    name
    points
  }
}

mutation CreateLoyaltyTier($input: LoyaltyTierInput!) {
  createLoyaltyTier(input: $input) {
    _id
    name
    points
  }
}

mutation EditLoyaltyTier($id: String!, $input: UpdateLoyaltyTierInput!) {
  updateLoyaltyTier(id: $id, input: $input) {
    _id
    name
    points
  }
}

mutation DeleteLoyaltyTier($id: String!) {
  deleteLoyaltyTier(id: $id) {
    _id
    name
    points
  }
}

############
# Breakdown
############
query FetchLoyaltyBreakdownById($id: String!) {
  fetchLoyaltyBreakdownById(id: $id) {
    _id
    min
    max
    bronze
    silver
    gold
    platinum
  }
}

query FetchLoyaltyBreakdowns {
  fetchLoyaltyBreakdowns {
    _id
    min
    max
    bronze
    silver
    gold
    platinum
  }
}

mutation CreateLoyaltyBreakdown($input: LoyaltyBreakdownInput!) {
  createLoyaltyBreakdown(input: $input) {
    _id
    min
    max
    bronze
    silver
    gold
    platinum
  }
}

mutation EditLoyaltyBreakdown(
  $id: String!
  $input: UpdateLoyaltyBreakdownInput!
) {
  updateLoyaltyBreakdown(id: $id, input: $input) {
    _id
    min
    max
    bronze
    silver
    gold
    platinum
  }
}

mutation DeleteLoyaltyBreakdown($id: String!) {
  deleteLoyaltyBreakdown(id: $id) {
    _id
    min
    max
    bronze
    silver
    gold
    platinum
  }
}

############################
# Rider Loyalty Breakdown
############################
query FetchRiderLoyaltyBreakdownById($id: String!) {
  fetchRiderLoyaltyBreakdownById(id: $id) {
    _id
    min
    max
    amount
  }
}

query FetchRiderLoyaltyBreakdowns {
  fetchRiderLoyaltyBreakdowns {
    _id
    min
    max
    amount
  }
}

mutation CreateRiderLoyaltyBreakdown($input: RiderLoyaltyBreakdownInput!) {
  createRiderLoyaltyBreakdown(input: $input) {
    _id
    min
    max
    amount
  }
}

mutation EditRiderLoyaltyBreakdown($id: String!, $input: UpdateRiderLoyaltyBreakdownInput!) {
  updateRiderLoyaltyBreakdown(id: $id, input: $input) {
    _id
    min
    max
    amount
  }
}

mutation DeleteRiderLoyaltyBreakdown($id: String!) {
  deleteRiderLoyaltyBreakdown(id: $id) {
    _id
    min
    max
    amount
  }
}

############################
# Order Loyalty Level (Upline Rewards)
############################
query FetchOrderLoyaltyLevelById($id: String!) {
  fetchOrderLoyaltyLevelById(id: $id) {
    _id
    name
    points
    amount
    completionWindow
    requiredCompletedOrders
  }
}

query FetchOrderLoyaltyLevelsByUserType($userType: String!) {
  fetchOrderLoyaltyLevelsByUserType(userType: $userType) {
    _id
    name
    points
    amount
    completionWindow
    requiredCompletedOrders
  }
}

mutation CreateOrderLoyaltyLevel($input: OrderLoyaltyLevelInput!) {
  createOrderLoyaltyLevel(input: $input) {
    _id
    name
    points
    amount
    completionWindow
    requiredCompletedOrders
  }
}

mutation EditOrderLoyaltyLevel($id: String!, $input: UpdateOrderLoyaltyLevelInput!) {
  updateOrderLoyaltyLevel(id: $id, input: $input) {
    _id
    name
    points
    amount
    completionWindow
    requiredCompletedOrders
  }
}

mutation DeleteOrderLoyaltyLevel($id: String!) {
  deleteOrderLoyaltyLevel(id: $id) {
    _id
    name
    points
    amount
    completionWindow
    requiredCompletedOrders
  }
}

################
# Referral Network
################
query FetchUserReferralNetworkStats {
  fetchUserReferralNetworkStats {
    totalCount
    level1Count
    level2Count
    level3Count
  }
}

query FetchDriverReferralNetworkStats {
  fetchDriverReferralNetworkStats {
    totalCount
    level1Count
    level2Count
    level3Count
  }
}

query SearchReferralUsers($filter: ReferralNetworkSearchInput) {
  searchReferralUsers(filter: $filter) {
    data {
      _id
      name
      email
      tier
      totalPoints
    }
    totalCount
  }
}

query SearchReferralDrivers($filter: ReferralNetworkSearchInput) {
  searchReferralDrivers(filter: $filter) {
    data {
      _id
      name
      email
      tier
      totalPoints
    }
    totalCount
  }
}

query FetchUserReferralNetworkDetail($userId: String!) {
  fetchUserReferralNetworkDetail(userId: $userId) {
    _id
    name
    email
    tier
    totalPoints
    level1 {
      pointsPerActivity
      memberCount
      members {
        _id
        name
        email
        phone
        createdAt
        activityCount
        points
      }
    }
    level2 {
      pointsPerActivity
      memberCount
      members {
        _id
        name
        email
        phone
        createdAt
        activityCount
        points
      }
    }
    level3 {
      pointsPerActivity
      memberCount
      members {
        _id
        name
        email
        phone
        createdAt
        activityCount
        points
      }
    }
  }
}

query FetchDriverReferralNetworkDetail($driverId: String!) {
  fetchDriverReferralNetworkDetail(driverId: $driverId) {
    _id
    name
    email
    tier
    totalPoints
    level1 {
      pointsPerActivity
      memberCount
      members {
        _id
        name
        email
        phone
        createdAt
        activityCount
        points
      }
    }
    level2 {
      pointsPerActivity
      memberCount
      members {
        _id
        name
        email
        phone
        createdAt
        activityCount
        points
      }
    }
    level3 {
      pointsPerActivity
      memberCount
      members {
        _id
        name
        email
        phone
        createdAt
        activityCount
        points
      }
    }
  }
}

################
# Stats Overview
################
query FetchLoyaltyStatsOverview {
  fetchLoyaltyStatsOverview {
    totalLoyalCustomers
    totalPointsIssued
    totalPointsRedeemed
    activeDriverReferrals
  }
}

################
# History
################
query FetchReferralLoyaltyHistory($filter: FetchLoyaltyReferralHistoryFilterInput) {
  fetchReferralLoyaltyHistory(filter: $filter) {
    data {
      _id
      user_name
      user_rank
      type
      level
      value
      createdAt
    }
    totalCount
    totalPages
    currentPage
    hasNextPage
    hasPrevPage
  }
}
